name: onprem docker ci

on:
  release:
    types: [published]
    tags:
      - 'casual-onprem/v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'casualos-onprem'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-onprem
          push: true
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:oneprem,ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.ref_name }}-onprem
          platforms: linux/amd64, linux/arm64