name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest,ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.sha }}
          platforms: linux/amd64, linux/arm64

      - name: Update README.md
        run: |
          # Update Docker Pull Command
          sed -i 's|docker pull .*|docker pull ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest|' README.md
          # Update Publish Date
          sed -i 's|Published on .*|Published on $(date +'%Y-%m-%d')|' README.md
        shell: bash

      - name: Push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update README with Docker info"
          git push
